import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Contact from "@/components/contact/Contact";

export const metadata: Metadata = {
  title: "Khiari Haifa",
  description: "Generated by Khiari Haifa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-black">
        <Navbar />
        {children}
        <Contact />
      </body>
    </html>
  );
}
